import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Navbar } from './components/site/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="relative min-h-screen bg-white">
					{/* N A V B A R */}
					<Navbar />
					{/* M A I N		C O N T E N T		A R E A  */}
					<main className="p-10 sm:px-16 lg:px-44">
						<div className="mx-auto max-w-3xl space-y-20">{children}</div>
					</main>
				</div>
			</body>
		</html>
	)
}
